### ISSUE TITLE
UI issue on iOS 10.1

### ISSUE THREAD

**Issue by Goldstrike** [Microsoft/ConferenceVision#13]
I work on a Xamarin.Forms app where I need to implement transparent/translucent navigation bar.

I've studied how you implement, but I encouter a strange behavior on iOS 10.1.

On an iPhone 6 simulator under **iOS 11.3**, there is a gap between the navigation bar and the content: the render is [good](https://i.stack.imgur.com/DVKjZ.png).

But on my iPhone 6 under **iOS 10.1**, there is no gap and the content is displayed "under" the navigation bar: so it's [not good](https://i.stack.imgur.com/aO9qN.png).

Is it normal? How could I manage it on "older" versions of iOS?

**Comment by DiomedesDominguez** [comment]
It's normal for that version. You must always use the last 3 version of each mobile OS, because their marketshare grants you a better stability, compatibility and acceptance with the public.

This are the numbers for the 10.1 in the world (from [NetMarketshare](https://www.netmarketshare.com/operating-system-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Mobile%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22platformVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22platformsMobileVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222017-07%22%2C%22dateEnd%22%3A%222018-06%22%2C%22plotKeys%22%3A%5B%7B%22platformVersion%22%3A%22iOS%2010.1%22%7D%2C%7B%22platformVersion%22%3A%22iOS%2010.2%22%7D%2C%7B%22platformVersion%22%3A%22iOS%2010.3%22%7D%2C%7B%22platformVersion%22%3A%22iOS%2011.3%22%7D%2C%7B%22platformVersion%22%3A%22iOS%2011.2%22%7D%2C%7B%22platformVersion%22%3A%22iOS%2011.0%22%7D%2C%7B%22platformVersion%22%3A%22iOS%2011.1%22%7D%5D%2C%22pageLength%22%3A50%2C%22segments%22%3A%22-1000%22%7D))
![screen shot 2018-07-05 at 1 18 11 pm](https://user-images.githubusercontent.com/4379316/42337842-f02e0990-8055-11e8-9b51-de56817264f1.png)

Just tell the users to use a more updated version.

**Comment by Goldstrike** [comment]
Thank you, it's interesting: it's really not like for Android ;-) I will update my iPhone too.

**Comment by davidortinau** [comment]
Yes, this wasn't written to hit the older iOS versions. To address this you could detect their version and use an OnPlatform or similar to adjust the inset padding when needed.

Xamarin Essentials provides an easy cross-platform way to get this version information: https://docs.microsoft.com/en-us/xamarin/essentials/device-information?context=xamarin%2Fxamarin-forms&tabs=ios

If working just within the iOS project, in a custom renderer for example, you can use these methods to do similar: https://github.com/xamarin/recipes/tree/master/Recipes/ios/general/projects/environment_checks
